

POST http://localhost:3000/user/
Content-Type:application.json()

{
  "username": "christopher_phillips",
  "name":"christy",
  "password": "christy@123",
  "gender":"male",
  "location":"kerala"
} 



####
POST http://localhost:3000/login/
Content-Type:application.json()

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
